import Link from 'next/link'
import { ArrowRight, Code2, Heart, Sparkles } from 'lucide-react'
import { BlogLayout } from '@/components/blog/blog-layout'
import { PostCard, ProjectCard, ReportCard } from '@/components/blog/cards'
import { posts, projects, reports } from '@/lib/blog-data'

export default function HomePage() {
  return <BlogLayout><main className="home-page"><section className="hero"><div className="hero-copy"><span className="eyebrow"><Sparkles size={13} /> personal dev log · 2024</span><h1>Привет, я Мия.<br /><em>Пишу код</em> и выращиваю<br />маленькие цифровые сады.</h1><p>Личный блог о разработке, дизайне интерфейсов, open source и попытках сделать интернет немного добрее.</p><div className="hero-actions"><Link className="button-primary" href="/posts">читать ленту <ArrowRight size={16} /></Link><Link className="button-ghost" href="/projects">смотреть проекты</Link></div></div><div className="hero-terminal"><div className="terminal-bar"><span></span><span></span><span></span><code>miu.dev / now</code></div><div className="terminal-body"><span className="terminal-prompt">&gt; whoami</span><strong>creative developer</strong><span className="terminal-prompt">&gt; current_mood</span><strong className="mood">soft focus <Heart size={15} /></strong><span className="terminal-prompt">&gt; status</span><strong className="status-line"><i></i> building in public</strong></div></div></section><section className="home-section"><div className="section-heading"><div><span className="eyebrow">последнее из ленты</span><h2>Короткие мысли</h2></div><Link className="text-link" href="/posts">вся лента <ArrowRight size={14} /></Link></div><div className="content-grid posts-grid">{posts.slice(0, 2).map(post => <PostCard key={post.slug} post={post} />)}</div></section><section className="home-section"><div className="section-heading"><div><span className="eyebrow">open source corner</span><h2>То, что строю</h2></div><Link className="text-link" href="/projects">все проекты <ArrowRight size={14} /></Link></div><div className="content-grid projects-grid">{projects.slice(0, 2).map(project => <ProjectCard key={project.slug} project={project} />)}</div></section><section className="home-section report-feature"><div className="section-heading"><div><span className="eyebrow"><Code2 size={13} /> автоматические логи</span><h2>Недельный отчёт</h2></div><Link className="text-link" href="/reports">архив отчётов <ArrowRight size={14} /></Link></div><ReportCard report={reports[0]} /></section></main></BlogLayout>
}
